name: Build HTML and PDF for Sphinx Documentation

on:
  push:
    branches:
      - main  # Trigger on pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install Python dependencies (Sphinx + PDF tools)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx myst-parser
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk

      # Step 4: Build HTML documentation
      - name: Build HTML documentation
        run: |
          sphinx-build -b html ./source ./docs

      # Step 5: Build PDF documentation
      - name: Build PDF documentation
        run: |
          sphinx-build -b latex ./source ./latex
          cd latex && make

      # Step 6: Upload PDF as GitHub Artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: Documentation-PDF
          path: ./latex/*.pdf

      # Step 7: Deploy HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
